// <auto-generated />
using System;
using Infraestructure.Persistence.Config;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infraestructure.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20230826223309_CCINE")]
    partial class CCINE
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.Property<int>("FuncionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FuncionId"));

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("datetime2");

                    b.Property<TimeSpan>("Horario")
                        .HasColumnType("time");

                    b.Property<int>("PeliculaId")
                        .HasColumnType("int");

                    b.Property<int>("SalaId")
                        .HasColumnType("int");

                    b.HasKey("FuncionId");

                    b.HasIndex("PeliculaId");

                    b.HasIndex("SalaId");

                    b.ToTable("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Genero", b =>
                {
                    b.Property<int>("GeneroId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("GeneroId"));

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("GeneroId");

                    b.ToTable("Generos");

                    b.HasData(
                        new
                        {
                            GeneroId = 1,
                            Nombre = "Acción"
                        },
                        new
                        {
                            GeneroId = 2,
                            Nombre = "Aventura"
                        },
                        new
                        {
                            GeneroId = 3,
                            Nombre = "Ciencia"
                        },
                        new
                        {
                            GeneroId = 4,
                            Nombre = "Ficción"
                        },
                        new
                        {
                            GeneroId = 5,
                            Nombre = "Comedia"
                        },
                        new
                        {
                            GeneroId = 6,
                            Nombre = "Documental"
                        },
                        new
                        {
                            GeneroId = 7,
                            Nombre = "Drama"
                        },
                        new
                        {
                            GeneroId = 8,
                            Nombre = "Fantasía"
                        },
                        new
                        {
                            GeneroId = 9,
                            Nombre = "Musical"
                        },
                        new
                        {
                            GeneroId = 10,
                            Nombre = "Suspense"
                        },
                        new
                        {
                            GeneroId = 11,
                            Nombre = "Terror"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Pelicula", b =>
                {
                    b.Property<int>("PeliculaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PeliculaId"));

                    b.Property<int>("GeneroId")
                        .HasColumnType("int");

                    b.Property<string>("Poster")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Sinopsis")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Trailer")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PeliculaId");

                    b.HasIndex("GeneroId");

                    b.ToTable("Peliculas");

                    b.HasData(
                        new
                        {
                            PeliculaId = 1,
                            GeneroId = 1,
                            Poster = "https://static.wikia.nocookie.net/marvelcinematicuniverse/images/9/9b/Avenger_Endgame_Poster_Oficial.png/revision/latest?cb=20190326185910&path-prefix=es",
                            Sinopsis = "Después de los devastadores eventos ocurridos en Vengadores: Infinity War, el universo está en ruinas debido a las acciones de Thanos, el Titán Loco. Tras la derrota, las cosas no pintan bien para los Vengadores. Mientras Iron Man vaga en soledad junto a Nebula en una nave lejos de la Tierra, el grupo encabezado por Capitán América, Viuda Negra, Hulk y Thor deberá tratar de revertir los efectos de la catástrofe provocada por Thanos. Los Vengadores deberán reunirse una vez más para deshacer sus acciones y restaurar el orden en el universo de una vez por todas. Esta vez, contarán también con aliados como Ojo de Halcón y Capitana Marvel, además de Ant-Man, que presumiblemente podría haber estado atrapado en el Reino Cuántico. Juntos, se prepararán para la batalla final, sin importar cuáles sean las consecuencias.",
                            Titulo = "Avengers: End Game",
                            Trailer = "https://www.youtube.com/watch?v=PyakRSni-c0"
                        },
                        new
                        {
                            PeliculaId = 2,
                            GeneroId = 1,
                            Poster = "https://images.justwatch.com/poster/99741292/s718/los-vengadores-infinity-war.jpg",
                            Sinopsis = "Un nuevo peligro acecha procedente de las sombras del cosmos. Thanos, el infame tirano intergaláctico, tiene como objetivo reunir las seis Gemas del Infinito, artefactos de poder inimaginable, y usarlas para imponer su perversa voluntad a toda la existencia. Los Vengadores y sus aliados tendrán que luchar contra el mayor villano al que se han enfrentado nunca, y evitar que se haga con el control de la galaxia. En su nueva e impactante aventura, el destino de la Tierra nunca había sido más incierto, las Gemas del Infinito estarán en juego, unos querrán protegerlas y otros controlarlas, ¿quién ganará?",
                            Titulo = "Avengers: Infinity War",
                            Trailer = "https://www.youtube.com/watch?v=823iAZOEKt8"
                        },
                        new
                        {
                            PeliculaId = 3,
                            GeneroId = 2,
                            Poster = "https://static.wikia.nocookie.net/cine/images/6/62/Piratas_del_Caribe.jpg/revision/latest?cb=20201006154235",
                            Sinopsis = "El capitán Jack Sparrow (interpretado por Johnny Depp) se embarca en una trepidante aventura para recuperar su querido barco, el Perla Negra, que ha sido robado por su rival, el capitán Barbossa. Sin embargo, Sparrow no solo busca recuperar su barco, sino también enfrentarse a una maldición que afecta a la tripulación de Barbossa, convirtiéndolos en inmortales pero condenados a ser esqueletos durante la noche. Con la ayuda de la valiente Elizabeth Swann (Keira Knightley) y el temerario Will Turner (Orlando)",
                            Titulo = "Piratas del Caribe: La Maldición del Perla Negra",
                            Trailer = "https://www.youtube.com/watch?v=5Itr2jHuJaw"
                        },
                        new
                        {
                            PeliculaId = 4,
                            GeneroId = 2,
                            Poster = "https://static.wikia.nocookie.net/cine/images/a/a2/IndianaJonesLostArk.jpg/revision/latest?cb=20121009224059",
                            Sinopsis = "El arqueólogo y aventurero Indiana Jones (interpretado por Harrison Ford) es reclutado por el gobierno de los Estados Unidos para encontrar el Arca de la Alianza antes de que los nazis lo hagan. Según la leyenda, el Arca contiene poderes sobrenaturales y puede ser utilizada como arma devastadora. Indiana Jones se embarca en una emocionante búsqueda que lo lleva a lugares exóticos y peligrosos alrededor del mundo. A lo largo de su viaje, se enfrenta a trampas mortales, enemigos despiadados y situaciones de suspenso constante mientras lucha por mantener el Arca fuera del alcance de los nazis y preservar su importancia histórica.",
                            Titulo = "Indiana Jones y los Cazadores del Arca Perdida",
                            Trailer = "https://www.youtube.com/watch?v=ceMf9xtDA6U"
                        },
                        new
                        {
                            PeliculaId = 5,
                            GeneroId = 3,
                            Poster = "https://pics.filmaffinity.com/Interstellar-366875261-large.jpg",
                            Sinopsis = "En un futuro donde la Tierra se enfrenta a la escasez de recursos y la decadencia ambiental, un grupo de exploradores espaciales liderados por el piloto Cooper (interpretado por Matthew McConaughey) se embarca en una misión interestelar para encontrar un nuevo hogar para la humanidad. Utilizando agujeros de gusano recientemente descubiertos, viajan a través del espacio en busca de un planeta habitable. La película explora conceptos de gravedad, dimensiones alternativas y la lucha por la supervivencia humana en un entorno alienígena.",
                            Titulo = "Interestelar",
                            Trailer = "https://www.youtube.com/watch?v=LYS2O1nl9iM"
                        },
                        new
                        {
                            PeliculaId = 6,
                            GeneroId = 3,
                            Poster = "https://cloudfront-us-east-1.images.arcpublishing.com/artear/CSTSFCSG35DQNFZVORM4DLQCIU.jpg",
                            Sinopsis = "Drama biográfico de corte histórico basado en American Prometheus, la biografía escrita por Kai Bird y Martin J. Sherwin en torno a la figura del científico J. Robert Oppenheimer y su rol en la creación y desarrollo de la bomba atómica. 16 de julio de 1945, en el desierto de Nuevo México se detona en secreto la primera bomba atómica. En tiempos de guerra, el brillante físico estadounidense Julius Robert Oppenheimer (Cillian Murphy), al frente del proyecto Manhattan, lidera los ensayos nucleares para construir la bomba atómica para su país.",
                            Titulo = "OppenHeimer",
                            Trailer = "https://www.youtube.com/watch?v=MVvGSBKV504"
                        },
                        new
                        {
                            PeliculaId = 7,
                            GeneroId = 4,
                            Poster = "https://pics.filmaffinity.com/Origen-652954101-large.jpg",
                            Sinopsis = "Dirigida por Christopher Nolan, Origen sigue a Dom Cobb (interpretado por Leonardo DiCaprio), un ladrón habilidoso que se especializa en el robo de secretos a través de la invasión de los sueños de otras personas. Sin embargo, su última misión implica la tarea inversa: implantar una idea en la mente de alguien. La película explora temas de la realidad, la percepción y los límites de la mente humana a medida que el equipo de Cobb se sumerge cada vez más en niveles profundos de sueños.",
                            Titulo = "Origen",
                            Trailer = "https://www.youtube.com/watch?v=RV9L7ui9Cn8"
                        },
                        new
                        {
                            PeliculaId = 8,
                            GeneroId = 4,
                            Poster = "https://pics.filmaffinity.com/Matrix-155050517-large.jpg",
                            Sinopsis = "Dirigida por los hermanos Wachowski, Matrix presenta a Thomas Anderson (interpretado por Keanu Reeves), un programador de software que, bajo el alias de Neo, se une a un grupo de rebeldes que luchan contra una inteligencia artificial que ha esclavizado a la humanidad en una realidad simulada llamada la Matriz. La película combina acción, filosofía y conceptos de simulación virtual para crear una historia única sobre la búsqueda de la verdad y la liberación de la mente humana.",
                            Titulo = "Matrix",
                            Trailer = "https://www.youtube.com/watch?v=sMkNB8v-0uQ"
                        },
                        new
                        {
                            PeliculaId = 9,
                            GeneroId = 5,
                            Poster = "https://static.wikia.nocookie.net/doblaje/images/5/50/MiPobreAngelito.jpg/revision/latest?cb=20150517192150&path-prefix=es",
                            Sinopsis = "Kevin McCallister (interpretado por Macaulay Culkin) es un niño de ocho años que es accidentalmente dejado atrás cuando su familia se va de vacaciones durante la Navidad. Mientras se encuentra solo en casa, Kevin debe defender su hogar de dos torpes ladrones que intentan robarlo. La película es una mezcla de humor físico y situaciones cómicas mientras Kevin utiliza su ingenio para crear elaboradas trampas y hacer que los ladrones paguen por sus acciones.",
                            Titulo = "Mi Pobre Angelito",
                            Trailer = "https://www.youtube.com/watch?v=KSpCNBIo92A"
                        },
                        new
                        {
                            PeliculaId = 10,
                            GeneroId = 5,
                            Poster = "https://pics.filmaffinity.com/Supersalidos-743461969-large.jpg",
                            Sinopsis = "Dos amigos de preparatoria, Seth (interpretado por Jonah Hill) y Evan (Michael Cera), están a punto de graduarse y enfrentan la realidad de que sus caminos podrían separarse. Deciden asistir a una fiesta con la esperanza de perder su virginidad antes de la graduación. La película sigue sus hilarantes desventuras mientras intentan conseguir alcohol, lidiar con situaciones incómodas y mantener su amistad en medio del caos.",
                            Titulo = "Superbad",
                            Trailer = "https://www.youtube.com/watch?v=au2Zq8D9RaY"
                        },
                        new
                        {
                            PeliculaId = 11,
                            GeneroId = 6,
                            Poster = "https://es.web.img3.acsta.net/medias/nmedia/18/95/26/08/20393348.jpg",
                            Sinopsis = "Dirigida por Malik Bendjelloul, Buscando a Sugar Man narra la historia de Sixto Rodríguez, un músico folk estadounidense que, a pesar de no haber tenido éxito comercial en su propio país, se convirtió en una leyenda musical en Sudáfrica durante los años 70. La película sigue a dos aficionados sudafricanos de la música que se embarcan en una búsqueda para descubrir qué sucedió realmente con Rodríguez y cuál fue su destino después de su breve carrera en la industria musical. A medida que desentrañan la verdad, descubren una historia increíble de música, misterio y redescubrimiento.",
                            Titulo = "Buscando a Sugar Man",
                            Trailer = "https://www.youtube.com/watch?v=sg_hzT0QhPM"
                        },
                        new
                        {
                            PeliculaId = 12,
                            GeneroId = 6,
                            Poster = "https://pics.filmaffinity.com/Nuestro_planeta_Serie_de_TV-955486466-large.jpg",
                            Sinopsis = "Esta serie documental de naturaleza, narrada por David Attenborough, explora la asombrosa belleza y diversidad de la vida en la Tierra. A lo largo de varios episodios, la serie muestra los hábitats naturales más sorprendentes del planeta y resalta la importancia de la conservación y la protección de la vida silvestre y los ecosistemas.",
                            Titulo = "Nuestro Planeta",
                            Trailer = "https://www.youtube.com/watch?v=IrER_EpwGjg"
                        },
                        new
                        {
                            PeliculaId = 13,
                            GeneroId = 7,
                            Poster = "https://pics.filmaffinity.com/La_lista_de_Schindler-473662617-large.jpg",
                            Sinopsis = " Dirigida por Steven Spielberg, La Lista de Schindler está basada en la historia real de Oskar Schindler (interpretado por Liam Neeson), un empresario alemán que salvó la vida de más de mil judíos durante el Holocausto al emplearlos en sus fábricas. La película sigue su evolución desde un oportunista empresario hasta un héroe que arriesga todo para proteger a aquellos perseguidos por el régimen nazi. Es una historia poderosa que muestra tanto la oscuridad de la historia como la capacidad del espíritu humano para resistir y mostrar compasión.",
                            Titulo = "La Lista de Schindler",
                            Trailer = "https://www.youtube.com/watch?v=7q-ETFeMxwI"
                        },
                        new
                        {
                            PeliculaId = 14,
                            GeneroId = 7,
                            Poster = "https://es.web.img3.acsta.net/pictures/19/09/04/11/42/1166515.jpg",
                            Sinopsis = "Dirigida por Paulina García, Mujer en Llamas sigue a Ema (interpretada por Mariana Di Girolamo), una joven bailarina que está decidida a recuperar a su hijo después de que su adopción se rompe. La película explora temas de amor, maternidad, arrepentimiento y búsqueda de identidad mientras Ema desafía convenciones sociales y emprende un viaje emocional y físico para recuperar a su hijo.",
                            Titulo = "Mujer en Llamas",
                            Trailer = "https://www.filmaffinity.com/es/film218131.html"
                        },
                        new
                        {
                            PeliculaId = 15,
                            GeneroId = 8,
                            Poster = "https://play-lh.googleusercontent.com/imeAs3_Nb9fyoj56LgLzSRBs3UXTZTH_TLg2xMkg6J90ZPzxscAXPvtsR9Q9azxe-WCy5A",
                            Sinopsis = "Basada en la novela de J.R.R. Tolkien, esta película dirigida por Peter Jackson sigue la épica aventura de Frodo Baggins (interpretado por Elijah Wood) y un variado grupo de personajes mientras intentan destruir un poderoso anillo que podría sumir al mundo en la oscuridad. Ambientada en un mundo de fantasía llamado la Tierra Media, la película presenta criaturas míticas, paisajes impresionantes y una historia de valentía y amistad mientras la Comunidad del Anillo lucha contra fuerzas oscuras para salvar a su mundo.",
                            Titulo = "El Señor de los Anillos: La Comunidad del Anillo",
                            Trailer = "https://www.youtube.com/watch?v=3GJp6p_mgPo"
                        },
                        new
                        {
                            PeliculaId = 16,
                            GeneroId = 8,
                            Poster = "https://images-na.ssl-images-amazon.com/images/S/pv-target-images/5ea3b0f74fe2901a697365e20b15ac3accdcf68365f9db9aa039f07ae5368165._RI_TTW_.jpg",
                            Sinopsis = " Dirigida por Guillermo del Toro, El Laberinto del Fauno se desarrolla en la posguerra de España y sigue a Ofelia (interpretada por Ivana Baquero), una niña que descubre un mundo mágico y misterioso en un laberinto cerca de su nuevo hogar. Mientras su madre embarazada se enfrenta a dificultades y su padrastro brutal busca eliminar a los rebeldes locales, Ofelia se encuentra en una serie de desafíos mágicos y oscuros que la llevan a cuestionar la realidad y la fantasía.",
                            Titulo = "El Laberinto del Fauno",
                            Trailer = "https://www.youtube.com/watch?v=gpEh4O8Hb5Y"
                        },
                        new
                        {
                            PeliculaId = 17,
                            GeneroId = 9,
                            Poster = "https://www.lavanguardia.com/peliculas-series/images/movie/poster/2017/12/w1280/4ssLEvNQ5oM9sJnV6FkDVgOtyAE.jpg",
                            Sinopsis = "Inspirada en la vida de P.T. Barnum, El Gran Showman narra la historia de cómo Barnum (interpretado por Hugh Jackman) creó el circo que eventualmente se convertiría en el famoso Circo Barnum & Bailey. La película combina elementos de música, baile y espectáculo con temas de ambición, amor y aceptación mientras Barnum lucha por encontrar el éxito y la aceptación social.",
                            Titulo = "El Gran Showman",
                            Trailer = "https://www.youtube.com/watch?v=uprrVIIT0G8"
                        },
                        new
                        {
                            PeliculaId = 18,
                            GeneroId = 9,
                            Poster = "https://pics.filmaffinity.com/Los_miserables-196100834-large.jpg",
                            Sinopsis = "Basada en la novela clásica de Victor Hugo, Los Miserables sigue las vidas entrelazadas de varios personajes en la Francia del siglo XIX. La película se centra en la historia de Jean Valjean (interpretado por Hugh Jackman), un exconvicto que busca redimirse mientras es perseguido por el inspector Javert (Russell Crowe). La película está llena de canciones emotivas y poderosas que exploran temas de justicia, amor y sacrificio.",
                            Titulo = "Los Miserables",
                            Trailer = "https://www.youtube.com/watch?v=EZngbEj3W1Y"
                        },
                        new
                        {
                            PeliculaId = 19,
                            GeneroId = 10,
                            Poster = "https://static.wikia.nocookie.net/doblaje/images/5/57/Se_lo_que_icieron_el_verano.png/revision/latest?cb=20130228060651&path-prefix=es",
                            Sinopsis = "Dirigida por Jim Gillespie, esta película sigue a un grupo de amigos que, después de un trágico accidente automovilístico en el que atropellan a un hombre, deciden ocultar su crimen y juran guardar el secreto. Un año después, comienzan a recibir amenazantes mensajes que los persiguen con la pregunta: ¿Sabes lo que hicieron el verano pasado?. La película se convierte en un juego de suspense mientras los protagonistas luchan por descubrir la verdad detrás de los mensajes y enfrentan las consecuencias de sus acciones.",
                            Titulo = "Sé lo que Hicieron el Verano Pasado",
                            Trailer = "https://www.youtube.com/watch?v=_y6H2ybiEvs"
                        },
                        new
                        {
                            PeliculaId = 20,
                            GeneroId = 10,
                            Poster = "https://es.web.img3.acsta.net/medias/nmedia/18/74/29/15/19757760.jpg",
                            Sinopsis = "Basada en la novela de Thomas Harris, esta película dirigida por Jonathan Demme presenta a la joven agente del FBI Clarice Starling (interpretada por Jodie Foster) mientras busca la ayuda del brillante pero psicótico asesino en serie Hannibal Lecter (Anthony Hopkins) para atrapar a otro asesino en serie conocido como Buffalo Bill. La película es una mezcla de suspense psicológico y drama policial, y se centra en la relación entre Starling y Lecter mientras persiguen a un asesino extremadamente peligroso.",
                            Titulo = "El Silencio de los Corderos",
                            Trailer = "https://www.youtube.com/watch?v=3VZa6KAxE1I"
                        },
                        new
                        {
                            PeliculaId = 21,
                            GeneroId = 11,
                            Poster = "https://r1.abcimg.es/resizer/resizer.php?imagen=https%3A%2F%2Fs1.abcstatics.com%2Fmedia%2Fpeliculas%2F000%2F002%2F487%2Fel-exorcista-1.jpg&nuevoancho=683&medio=abc",
                            Sinopsis = "Dirigida por William Friedkin, El Exorcista es un clásico del terror que sigue la historia de Regan (interpretada por Linda Blair), una niña poseída por una entidad demoníaca. La película sigue los esfuerzos de un sacerdote y un psiquiatra para exorcizar al demonio que ha tomado control del cuerpo de la niña.El Exorcista es conocida por sus escenas intensas y perturbadoras, y se ha convertido en una película icónica del género de terror.",
                            Titulo = "El Exorcista",
                            Trailer = "https://www.youtube.com/watch?v=gYApro2YXQQ"
                        },
                        new
                        {
                            PeliculaId = 22,
                            GeneroId = 11,
                            Poster = "https://static.wikia.nocookie.net/doblaje/images/e/eb/ElConjuroPoster.jpg/revision/latest?cb=20170907214450&path-prefix=es",
                            Sinopsis = "Dirigida por James Wan, El Conjuro está basada en casos reales de los investigadores paranormales Ed y Lorraine Warren. La película sigue a los Warren (interpretados por Patrick Wilson y Vera Farmiga) mientras investigan una serie de eventos sobrenaturales aterradores que ocurren en la casa de una familia. La película crea una atmósfera de miedo y tensión a medida que los personajes enfrentan fuerzas malévolas y luchan por proteger a la familia de las fuerzas sobrenaturales.",
                            Titulo = "El Conjuro",
                            Trailer = "https://www.youtube.com/watch?v=_zU1gLWGnpg"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.Property<int>("SalaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SalaId"));

                    b.Property<int>("Capacidad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SalaId");

                    b.ToTable("Salas");

                    b.HasData(
                        new
                        {
                            SalaId = 1,
                            Capacidad = 5,
                            Nombre = "Sala 1"
                        },
                        new
                        {
                            SalaId = 2,
                            Capacidad = 15,
                            Nombre = "Sala 2"
                        },
                        new
                        {
                            SalaId = 3,
                            Capacidad = 35,
                            Nombre = "Sala 3"
                        });
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.Property<Guid>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FuncionId")
                        .HasColumnType("int");

                    b.Property<string>("Usuario")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("TicketId");

                    b.HasIndex("FuncionId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.HasOne("Domain.Entities.Pelicula", "Pelicula")
                        .WithMany("Funciones")
                        .HasForeignKey("PeliculaId");

                    b.HasOne("Domain.Entities.Sala", "Sala")
                        .WithMany("Funciones")
                        .HasForeignKey("SalaId");

                    b.Navigation("Pelicula");

                    b.Navigation("Sala");
                });

            modelBuilder.Entity("Domain.Entities.Pelicula", b =>
                {
                    b.HasOne("Domain.Entities.Genero", "Genero")
                        .WithMany("Peliculas")
                        .HasForeignKey("GeneroId");

                    b.Navigation("Genero");
                });

            modelBuilder.Entity("Domain.Entities.Ticket", b =>
                {
                    b.HasOne("Domain.Entities.Funcion", "Funcion")
                        .WithMany("Tickets")
                        .HasForeignKey("FuncionId");

                    b.Navigation("Funcion");
                });

            modelBuilder.Entity("Domain.Entities.Funcion", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Domain.Entities.Genero", b =>
                {
                    b.Navigation("Peliculas");
                });

            modelBuilder.Entity("Domain.Entities.Pelicula", b =>
                {
                    b.Navigation("Funciones");
                });

            modelBuilder.Entity("Domain.Entities.Sala", b =>
                {
                    b.Navigation("Funciones");
                });
#pragma warning restore 612, 618
        }
    }
}
